#### new keys:
ROOT: /storage/groups/ml01/workspace/scIB

METHODS: # method name : ouput type(s)
  mnn: full
  scanorama:
    - embed
    - full
  seurat: full
  trvae: embed
  harmony: embed
  bbknn: knn

DATA_SCENARIOS:
  pancreas:
    batch_key: tech
    label_key: celltype
    organism: human
    assay: expression
    file: /storage/groups/ml01/workspace/maren.buettner/data_integration/data/human_pancreas/human_pancreas_norm.h5ad
  lung_atlas:
    batch_key: batch
    label_key: cell_type
    organism: human
    assay: expression
    file: /storage/groups/ml01/workspace/group.daniela/lung/Lung_atlas_final_fixed.h5ad
  immune_cell:
    batch_key: batch
    label_key: final_annotation
    organism: human
    assay: expression
    file: /storage/groups/ml01/workspace/group.daniela/immune_cells/Immune_ALL_human.h5ad
  mouse_atlas:
    batch_key: study # TODO: we need batch over all samples as well
    label_key: cell_type_union
    organsism: mouse
    assay: expression
    file: /storage/groups/ml01/workspace/group.daniela/atlases_merged_anno_new.h5ad
  mouse_brain:
    batch_key: study
    label_key: cell_type
    organism: mouse
    assay: expression
    file: /storage/groups/ml01/workspace/maren.buettner/data_integration/data/mouse_brain/mouse_brain_norm.h5ad
    #  mouse_brain_atac:
    #    batch_key: batchname
    #label_key: cell_type_consensus
    #organism: mouse
    #assay: atac
    #file: /mnt/znas/icb_zstore01/groups/ce01/workspace/Benchmarking_data_integration/data/brain_atac/atac_brain_processed.h5ad
####


DATASETS: 
  #- mnn_full
  - scanorama_embed
  - scanorama_full
  - seurat_full
  - trvae_embed
  - harmony_embed
    #- bbknn_knn

batch_key: study # tech
label_key: cell_type_union # celltype
organism: mouse # human

#UNINTEGRATED: /storage/groups/ml01/workspace/group.daniela/maren_human_pancreas/human_pancreas_norm.h5ad
#INTEGRATED_DIR: /storage/groups/ml01/workspace/group.daniela/maren_human_pancreas/integrated
#METRICS_DIR : /storage/groups/ml01/workspace/group.daniela/maren_human_pancreas/metrics

UNINTEGRATED: /storage/groups/ml01/workspace/group.daniela/atlases_merged_anno_new.h5ad
INTEGRATED_DIR: /storage/groups/ml01/workspace/group.daniela/atlases_integrated
METRICS_DIR : /storage/groups/ml01/workspace/group.daniela/metrics
