#### new keys:
ROOT: /storage/groups/ml01/workspace/scIB

DATA_SCENARIOS:
  pancreas:
    organism: human
    assay: expression
    file: 
  mouse_brain:
    organism: mouse
    assay: expression
    file: 
  immune_cell:
    organism: human
    assay: expression
    file: 
  mouse_atlas:
    organsism: mouse
    assay: expression
    file: 
  mouse_brain_atac:
    organism: mouse
    assay: atac
    file: 

# method name : ouput type(s)
METHODS:
  mnn: full
  scanorama:
    - embed
    - full
  seurat: full
  trvae: embed
  harmony: embed
  bbknn: knn

####


DATASETS: 
  #- mnn_full
  - scanorama_embed
  - scanorama_full
  - seurat_full
  - trvae_embed
  - harmony_embed
    #- bbknn_knn

batch_key: study # tech
label_key: cell_type_union # celltype
organism: mouse # human

#UNINTEGRATED: /storage/groups/ml01/workspace/group.daniela/maren_human_pancreas/human_pancreas_norm.h5ad
#INTEGRATED_DIR: /storage/groups/ml01/workspace/group.daniela/maren_human_pancreas/integrated
#METRICS_DIR : /storage/groups/ml01/workspace/group.daniela/maren_human_pancreas/metrics

UNINTEGRATED: /storage/groups/ml01/workspace/group.daniela/atlases_merged_anno_new.h5ad
INTEGRATED_DIR: /storage/groups/ml01/workspace/group.daniela/atlases_integrated
METRICS_DIR : /storage/groups/ml01/workspace/group.daniela/metrics
